### ISSUE TITLE
DNSimple OAuth token is missing

### ISSUE THREAD

**Issue by jrwren** [weppos/letsencrypt-dnsimple#3]
I try to use this with environment variable

DNSIMPLE_EMAIL=jrwren@xmtp.net DNSIMPLE_API_TOKEN=TOKEN-I-AM-USING-WITH-DIFF-APP

and I get this output:

2017/05/17 16:51:14 .data/users/jrwren@xmtp.net
2017/05/17 16:51:14 {jrwren@xmtp.net <nil> 0xc42005c540}
2017/05/17 16:51:14 DNSimple OAuth token is missing

**Comment by jrwren** [comment]
Looks like this commit broke it: https://github.com/xenolf/lego/commit/e526fb5a1afdfd74c506d5c873146deb20b48523

I checkout its parent 
git checkout 45beff7ed309e190408d7ac1c89a7b7751596a73
and use what I think is a v1 api-key and it works.

a v2 api-key did not work.

**Comment by weppos** [comment]
It should be fixed by #5
